
name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "dist/**"
      - "src/**"
      - "package.json"
      - "package-lock.json"  # Ensure this triggers the workflow to consider dependency changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your project's required Node.js version, ensuring compatibility

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Login with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name dolatowskifestorage -d '$web' -s dist/ --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name fe-cdn --name fe-cdn.azureedge.net --resource-group portfolio-front-end

      - name: Logout
        run: az logout

